"""create_accounts_table

Revision ID: f8a136cc1b4d
Revises: 1d38d673d495
Create Date: 2026-07-29 14:37:45.603674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8a136cc1b4d'
down_revision: Union[str, Sequence[str], None] = '1d38d673d495'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:                                                                                                                                                                                   
    """Upgrade schema."""                                                                                                                                                                                
    # ### commands auto generated by Alembic - please adjust! ###                                                                                                                                        
    op.create_table('accounts',                                                                                                                                                                          
    sa.Column('id', sa.UUID(), nullable=False),                                                                                                                                                          
    sa.Column('apelido', sa.String(length=100), nullable=False),                                                                                                                                         
    sa.Column('user_id', sa.UUID(), nullable=False),                                                                                                                                                     
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),                                                                                                                                 
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),                                                                                                                              
    sa.PrimaryKeyConstraint('id')                                                                                                                                                                        
    )                                                                                                                                                                                                    
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)                                                                                                                  
    # ### end Alembic commands ###                                                                                                                                                                       
                                                                                                                                                                                                             
                                                                                                                                                                                                             
def downgrade() -> None:                                                                                                                                                                                 
    """Downgrade schema."""                                                                                                                                                                              
    # ### commands auto generated by Alembic - please adjust! ###                                                                                                                                        
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')                                                                                                                                    
    op.drop_table('accounts')                                                                                                                                                                            
    # ### end Alembic commands ###         